// <auto-generated />
using System;
using HealthDiary.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthDiary.Web.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220430204805_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("HealthDiary.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6c85d92-1816-49d6-b38b-122449fa714b"),
                            CreatedOn = new DateTime(2022, 4, 30, 22, 48, 4, 930, DateTimeKind.Local).AddTicks(5591),
                            LastAccessed = new DateTime(2022, 4, 30, 22, 48, 4, 930, DateTimeKind.Local).AddTicks(5642),
                            Password = "password",
                            UserName = "test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
